import Head from "next/head"
import Image from "next/image"
// import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import Link from "next/link"

// const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Crux Rewards | Earn Points on Tuition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-gold">
          <div className="flex flex-col md:flex-row max-w-7xl mx-auto py-10">
            <div className="w-full md:w-1/2 relative">
              <h2 className="uppercase font-condensed font-bold text-7xl sm:text-8xl">
                Pay tuition.<br />Earn rewards.<br />Repeat.
              </h2>
              <p className="font-mono">
                The first credit card for students and parents that helps you pay for school.
              </p>
              <div className="flex items-center gap-x-6">
                <Link href="/waitlist">
                <button className="uppercase border border-black hover:bg-black text-black hover:text-white font-mono py-2 px-16" type="submit">
                  Sign up
                </button>
                </Link>
                <Link href="/school" className="font-mono hover:underline">
                  Representing a School?
                </Link>
              </div>
              
            </div>
            <div className="w-full md:w-1/2 relative aspect-square">
              <Image 
                className="object-cover object-center"
                src="/school-ai.jpg"
                alt="School"
                fill
              />
            </div>
          </div>
        </div>

        <div className="bg-defgray py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-5xl sm:text-7xl text-gold text-center">
              How it works.
            </h2>
            <div className="max-w-4xl mx-auto">
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; Register your school through our portal.</p>
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; Use our generated ACH account when you sign up for courses.</p>
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; Use your Crux Card for at least 5 transactions a month.</p>
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; Earn points on any tuition you paid that month.</p>
            </div>
          </div>
        </div>

        <div className="bg-black py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-5xl sm:text-7xl text-white text-center">
              Refined design.
            </h2>
            <div className="flex max-w-xl mx-auto justify-center">
              <video autoPlay muted loop src="/cruxcardv2.mp4"/>
            </div>
            <div className="max-w-xl mx-auto">
              <p className="font-mono text-gold text-xl">&#47;&#47; &#62; All metal. All awesome.</p>
              <p className="font-mono text-gold text-xl">&#47;&#47; &#62; No annual fee. Free to use.</p>
              <p className="font-mono text-gold text-xl">&#47;&#47; &#62; Tap to pay. Like magic.</p>
            </div>   
          </div>
        </div>

        <div className="bg-gold py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-5xl sm:text-7xl text-center">
              Rewards like no other.
            </h2>
            <div className="flex flex-col sm:flex-row">
              <div className="flex flex-col w-full sm:w-1/3 items-center sm:m-6">
                <div className="relative w-1/2 sm:w-full aspect-square">
                  <Image 
                    className="object-cover object-center rounded-full"
                    src="/school.jpg"
                    alt="School"
                    fill
                  />
                </div>
                <p className="font-mono text-center text-l">
                  Earn points when you pay tuition.
                </p>
              </div>
              <div className="flex flex-col w-full sm:w-1/3 items-center sm:m-6">
                <div className="relative w-1/2 sm:w-full aspect-square">
                  <Image 
                    className="object-cover object-center rounded-full"
                    src="/travel.jpg"
                    alt="Travel"
                    fill
                  />
                </div>
                <p className="font-mono text-center text-l">
                  Redeem for tuition, at stores, or on travel.
                </p>
              </div>
              <div className="flex flex-col w-full sm:w-1/3 items-center sm:m-6">
                <div className="relative w-1/2 sm:w-full aspect-square">
                  <Image 
                    className="object-cover object-center rounded-full"
                    src="/shop.jpg"
                    alt="Shopping"
                    fill
                  />
                </div>
                <p className="font-mono text-center text-l">
                  Refer a friend for even more rewards.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-defgray py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-5xl sm:text-7xl text-gold text-center">
              Next gen mobile experience.
            </h2>
            <div className="max-w-4xl mx-auto">
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; Manage your account anytime, anywhere.</p>
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; Create an unlimited amount of virtual cards.</p>
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; See how much interest you would pay, before you pay.</p>
              <p className="font-mono text-white text-xl">&#47;&#47; &#62; Cancel subscriptions with the tap of a button.</p>
            </div>
          </div>
        </div>

        <div className="bg-black py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-5xl sm:text-7xl text-white text-center">
              Build credit.
            </h2>
          </div>
        </div>

        <div className="bg-gold p-8">
          <div className="container flex flex-col max-w-4xl mx-auto justify-center items-center">
            <h1 className="uppercase font-condensed font-bold text-5xl sm:text-7xl text-black">
              Join the waitlist.
            </h1>
            <p className="font-mono text-md text-black">
              Be the first to hear about exclusive offers and updates from Crux.
            </p>
            <div className="w-full pt-4">
              <form>
                {/* <div className="px-3 mb-3">
                  <label className="block font-mono" htmlFor="email">Email *</label>
                  <input className="block w-full py-2 px-3 bg-gray-200 text-gray-700 font-mono" id="email" type="text" placeholder="example@cruxrewards.com"/>
                </div> */}
                <div className="flex justify-center">
                  <Link href="/waitlist">
                  <button className="uppercase border border-black hover:bg-black text-black hover:text-white font-mono py-2 px-20" type="submit">
                    Sign up
                  </button>
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
