import Head from "next/head"
import Image from "next/image"
// import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import Link from "next/link"

// const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Crux Rewards | Earn Points on Tuition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-black overflow-hidden">
          <div className="relative isolate px-6 pt-14 lg:px-8">
            <div className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80">
              <svg
                className="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
                viewBox="0 0 1155 678"
              >
                <path
                  fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)"
                  fillOpacity=".3"
                  d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
                />
                <defs>
                  <linearGradient
                    id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533"
                    x1="1155.49"
                    x2="-78.208"
                    y1=".177"
                    y2="474.645"
                    gradientUnits="userSpaceOnUse"
                  >
                    {/* <stop stopColor="#9089FC" /> */}
                    <stop stopColor="#E0C56E" />
                    <stop offset={1} stopColor="#FF80B5" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
              <div className="hidden sm:mb-8 sm:flex sm:justify-center">
                <div className="relative py-1 px-3 text-sm font-mono leading-6 text-white ring-1 ring-white hover:ring-gold">
                  Announcing our next round of funding.{' '}
                  <a href="#" className="font-semibold text-gold">
                    <span className="absolute inset-0" aria-hidden="true" />
                    Read more <span aria-hidden="true">&rarr;</span>
                  </a>
                </div>
              </div>
              <div className="text-center">
                <h1 className="uppercase text-4xl font-condensed font-bold tracking-tight text-white sm:text-7xl">
                  Redefining how you pay for education
                </h1>
                <p className="mt-6 text-md leading-8 text-white font-mono">
                  Education can be expensive due to the high cost of tuition fees, textbooks, and other educational materials. This can create financial barriers for many individuals, especially those from disadvantaged backgrounds, limiting their access to higher education.
                </p>
                <div className="mt-10 flex items-center justify-center gap-x-6">
                  <Link
                    href="/signup"
                    className="bg-gold px-3.5 py-2.5 text-sm font-mono font-semibold text-black shadow-sm hover:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                  >
                    Get started
                  </Link>
                  <Link href="/card" className="text-sm font-mono font-semibold leading-6 text-white">
                    Learn more <span aria-hidden="true">→</span>
                  </Link>  
                </div>
              </div>
            </div>
            <div className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
              <svg
                className="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]"
                viewBox="0 0 1155 678"
              >
                <path
                  fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)"
                  fillOpacity=".3"
                  d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
                />
                <defs>
                  <linearGradient
                    id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc"
                    x1="1155.49"
                    x2="-78.208"
                    y1=".177"
                    y2="474.645"
                    gradientUnits="userSpaceOnUse"
                  >
                    {/* <stop stopColor="#9089FC" /> */}
                    <stop stopColor="#E0C56E" />
                    <stop offset={1} stopColor="#FF80B5" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
          </div>
        </div>

        <div>
          <div className="flex flex-row max-w-7xl mx-auto bg-gold">
            <div className="w-1/2 relative">
              <h2 className="uppercase font-condensed font-bold text-7xl">
                Pay tuition.<br />Earn rewards.<br />Repeat.
              </h2>
              <p className="font-mono">
                The first credit card for students and parents that helps you pay for school.
              </p>
              <Link href="/waitlist">
              <button className="uppercase border border-black hover:bg-black text-black hover:text-white font-mono py-2 px-20" type="submit">
                Sign up
              </button>
              </Link>
              
            </div>
            <div className="w-1/2 bg-green-200 relative">
              <Image 
                className="object-cover object-center"
                src="/school-ai.jpg"
                alt="School"
                fill
              />
            </div>
          </div>
        </div>

        <div className="bg-defgray py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-7xl text-gold text-center">
              How it works.
            </h2>
          </div>
        </div>

        <div className="bg-black py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-7xl text-white text-center">
              Refined design.
            </h2>
            <div className="flex max-w-xl mx-auto justify-center">
              <video autoPlay muted loop src="/cruxcardv2.mp4"/>
            </div>
            <div className="max-w-xl mx-auto">
              <p className="font-mono text-gold text-xl">// &#62; All metal. All awesome.</p>
              <p className="font-mono text-gold text-xl">// &#62; No annual fee. Free to use.</p>
              <p className="font-mono text-gold text-xl">// &#62; Tap to pay. Like magic.</p>
            </div>   
          </div>
        </div>

        <div className="bg-gold py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-7xl text-center">
              Rewards like no other.
            </h2>
            <div className="flex flex-col sm:flex-row">
              <div className="flex flex-col w-full md:w-1/3 items-center m-4">
                <div className="relative w-full aspect-square">
                  <Image 
                    className="object-cover object-center rounded-full"
                    src="/school.jpg"
                    alt="School"
                    fill
                  />
                </div>
                <p className="font-mono text-center text-l">
                  Earn points when you pay tuition.
                </p>
              </div>
              <div className="flex flex-col w-full md:w-1/3 items-center m-4">
                <div className="relative w-full aspect-square">
                  <Image 
                    className="object-cover object-center rounded-full"
                    src="/travel.jpg"
                    alt="Travel"
                    fill
                  />
                </div>
                <p className="font-mono text-center text-l">
                  Redeem for tuition, at stores, or on travel.
                </p>
              </div>
              <div className="flex flex-col w-full md:w-1/3 items-center m-4">
                <div className="relative w-full aspect-square">
                  <Image 
                    className="object-cover object-center rounded-full"
                    src="/shop.jpg"
                    alt="Shopping"
                    fill
                  />
                </div>
                <p className="font-mono text-center text-l">
                  Refer a friend for even more rewards.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-black py-10">
          <div className="max-w-7xl mx-auto">
            <h2 className="uppercase font-condensed font-bold text-7xl text-white text-center">
              Build credit.
            </h2>
          </div>
        </div>

        {/* <div className="bg-black">
          <div className="flex flex-col md:flex-row max-w-4xl mx-auto">
            <div className="flex flex-col w-full md:w-3/4 justify-center items-center">
              <h2 className="uppercase font-condensed font-bold text-4xl text-white">
                Take control of your money, anytime, anywhere, with just a tap on your phone.
              </h2>
            </div>
            <div className="w-full md:w-1/4 m-4">
              <Image
                className="rounded-full"
                src="/phone.jpg"
                alt="Next.js Logo"
                width={300}
                height={300}
                priority
              />
            </div>
          </div>
        </div>
        <div className="bg-defgray p-6">
          <div className="flex flex-col md:flex-row max-w-4xl mx-auto">
            <h1 className="uppercase font-condensed font-bold text-gold text-4xl sm:text-7xl">
              How it works
            </h1>
          </div>
        </div> */}
        <div className="bg-gold p-8">
          <div className="container flex flex-col max-w-4xl mx-auto justify-center items-center">
            <h1 className="uppercase font-condensed font-bold text-4xl sm:text-7xl text-black">
              Join the waitlist
            </h1>
            <p className="font-mono text-md text-black">
              Be the first to hear about exclusive offers and updates from Crux.
            </p>
            <div className="w-full pt-4">
              <form>
                {/* <div className="px-3 mb-3">
                  <label className="block font-mono" htmlFor="email">Email *</label>
                  <input className="block w-full py-2 px-3 bg-gray-200 text-gray-700 font-mono" id="email" type="text" placeholder="example@cruxrewards.com"/>
                </div> */}
                <div className="flex justify-center">
                  <Link href="/waitlist">
                  <button className="uppercase border border-black hover:bg-black text-black hover:text-white font-mono py-2 px-20" type="submit">
                    Sign up
                  </button>
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
